### PR TITLE
Fix #63 Found a bug at the same time in DeepSec (commit 038b065) and …

### LINKED ISSUE #63: suggestions for rephrasing messages
A few suggestions for more clarity in some of the messages :

 * When an attack is found: replace the message _doesn't have an equivalent in process i_ with _does not have an equivalent trace in process i_.

 * In the attack simulator when frames are not statically equivalent, replace 

_The two recipes R1 and R2 yield the same message t on Process i but they yield different messages on Process j (u and v respectively)._

by 

_The test (R1 = R2) holds on process i, but not on process j._
        - _R1 and R2 evaluate to t in process i._
        - _R1 evaluates to u in process j._
        - _R2 evaluates to v in process j._

 * If static equivalence is violated because a recipe fails write
_Recipe R fails on process i but not on process j.

 * If an action cannot be simulated, replace 

_No visible actions available
To imitate the attack trace of Process i, an output / input transition on the channel ch should be available in Process j but no more visible actions are available._

by

_No matching visible actions available
Impossible to match visible transition `out(ch,ax)` / `in(R1,R2)`of process i._

### PR DESCRIPTION
**Pull request by VincentCheval**
…DeepSec UI (for the display of equivalence status)

### CODE REVIEW

File: src/models/ProcessDisplayedModel.js [hunk 1]
```diff
@@ -179,13 +179,17 @@ export default class ProcessDisplayedModel extends ProcessModel {
    */
   getVisibleAction (n) {
     let count = 0
+    let last_axiom = 0
```
Comment (Opsse) [inline src/models/ProcessDisplayedModel.js]: Bad naming convention for Javascript

Comment (VincentCheval) [reply src/models/ProcessDisplayedModel.js]: done
